FROM rocker/rstudio:4.3.1

RUN apt-get update && apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

RUN R -e "install.packages(c('BiocManager', 'rmarkdown', 'knitr', 'quarto', 'bookdown','here'), dependencies=TRUE, repos='http://cran.rstudio.com/')"


