FROM rocker/rstudio:4.3.1

#install some base libs
RUN apt-get update && \
	apt-get -y --no-install-recommends install --fix-missing \
        apt-file \
        apt-utils \
        libpoppler-cpp-dev \
        git \
        wget \
        gdebi-core \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN R -e "install.packages(c('tidyverse', 'rmarkdown', 'knitr', 'quarto', 'bookdown', \
                             'here', 'pdftools', 'tesseract', 'patchwork', 'plotly', \
                             'pwr', 'openxlsx', 'stringr', 'assertr', 'writexl', \
                             'credentials'), \
                             dependencies=TRUE, repos='http://cran.rstudio.com/')"

RUN ln -s /usr/lib/rstudio-server/bin/rsession /usr/local/bin/rsession

