FROM rocker/rstudio:4.3.1

#install some base libs
RUN apt-get update && \
	apt-get -y --no-install-recommends install --fix-missing \
        apt-file \
        apt-utils \
        libpoppler-cpp-dev \
        git \
        wget \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN R -e "install.packages(c('tidyverse', 'rmarkdown', 'knitr', 'quarto', 'bookdown','here', 'pdftools', 'tesseract', 'patchwork', 'plotly','pwr','openxlsx','stringr'), dependencies=TRUE, repos='http://cran.rstudio.com/')"

RUN if [ "$TARGETPLATFORM" = "linux/arm64 " ] ; then wget https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.3.2/gcm-osx-arm64-2.3.2.tar.gz; tar -xf gcm-osx-arm64-2.3.2.tar.gz; ./git-credential-manager configure; export GCM_CREDENTIAL_SCORE=cache ; fi

RUN if [ "$TARGETPLATFORM" = "linux/amd64 " ] ; then wget https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.3.2/gcm-linux_amd64.2.3.2.tar.gz; tar -xf gcm-linux-amd64-2.3.2.tar.gz; ./git-credential-manager configure; export GCM_CREDENTIAL_SCORE=cache ; fi



#RUN mkdir -p /app/installer/linux
#COPY linux/ /app/installer/linux
#RUN echo $TARGETPLATFORM
#RUN /app/installer/$TARGETPLATFORM.sh

