---
title: "Reproducibility in R"
format: 
  html:
    self-contained: true
author: Joselynn Wallace & George Dang
---
# Introduction
I am a Genomics Data Scientist with the Computational Biology Core at the Center for Computation and Visualization. I started at Brown in early 2019, before that I got my PhD in Biological and Environmental Sciences at University of Rhode Island. The goal of this workshop is to introduce you to a few of my favorite packages and approaches that help me make my R analyses more reproducible. I also wanted to thank my colleague, George Dang. He put together all of the stuff about OOD and helped me clarify some things about how I use containers. Thanks George!

If you have questions about anything we talk about here, come to our office hours (https://events.brown.edu/ccv/). In addition to the general Oscar office hours, you are also welcome to come by the Computational Biology Core office hours. Even if you aren't a biologist, we can probably help you with your R code.