---
title: "refactor"
format: html
editor: visual
---

## Power Analysis

### One-way ANOVA

```{r}
library(pwr)
```

We have 5 groups and want power of 80% with effect size 0.25 and significance level .05.

```{r}
a=pwr.anova.test(k=5,
               f=.25,
               sig.level=.05,
               power=.8)
a
```

What about if we only have 30 participants?

```{r}
b=pwr.anova.test(k=5,
               n=30,
               f=.25,
               sig.level=.05)
bpower <- b$power
```

```{r}
d=pwr.anova.test(k=5,
                 n=35,
                 f=.25,
                 sig.level=.05)
dpower <- d$power
```

```{r}
e=pwr.anova.test(k=5,
                 n=25,
                 f=.25,
                 sig.level=.05)
epower <- e$power
```

```{r}
f=pwr.anova.test(k=5,
                 n=40,
                 f=.25,
                 sig.level=.05)
```

```{r}
power <- c(.8,bpower,dpower,epower,f$power)
n <- c(a$n,30,35,25,f$n)
plot(n, power, type="b")
```

What effect size can we detect at 80% power with 30 participants?

```{r}
c=pwr.anova.test(k=5,
               n=30,
               sig.level=.05,
               power=.8)
c
```
